### ISSUE TITLE
Issues with Migrating from Manual Mod Installation to Nexus Mods (Stardew Valley)

### ISSUE THREAD

**Issue by StandingPadAnimations** [Nexus-Mods/NexusMods.App#2923]
# Bug Report

## Summary
I began the move from manually managing mods to using the Nexus Mods App (`0.8.2.0`) for Stardew Valley, but I've had several issues throughout the process.

*For context, I am on the latest version of Stardew Valley (`1.6.3` as of writing), installed using the Heroic Launcher Flatpak (`2.15.2`), and I'm also on Arch Linux. When installing Stardew Valley in Heroic Launcher, I selected the `Linux` download.*

When I created my first loadout, I got this message that said my game files could not be verified. 

![Missing game files](https://github.com/user-attachments/assets/7da5fdd3-6a59-41b2-b8d8-a5f2e7c82e83)

I figured, "alright, maybe I just need to migrate my mods first," so that's what I did. I migrated my mods from manually installed to installed with the app. However, I still had this message, even after I also did the verify and repair step with Heroic Launcher. I decided to see what would happen when I applied the loadout and play, and nothing happened.  I launched the AppImage in the CLI to see the logs and noticed messages that appeared like this:

```
Unable to extract {Game}/StardewModdingAPI.deps.json
```

[Log files of that attempt](https://github.com/user-attachments/files/19401303/nexusmods.app.main.current.log)

I decided to see if restarting my system would fix the issue, but that didn't. I was advised to see if deleting `StardewModdingAPI.deps.json` from External Changes would help, but unfortunately it didn't. I was then advised to upload the entire logs folder, which I did, so I'll also attach that here too.

[Zip file of logs at that point](https://github.com/user-attachments/files/19401305/Logs.zip)

Next I tried uninstalling and reinstalling Stardew Valley, but that didn't fix the issue. So I decided to A. clear the config for the app (as fresh of a slate as possible), and uninstall/reinstall Stardew Valley a second time. With that, I got to this window:

![Completely fresh attempt, still "Missing game files" error](https://github.com/user-attachments/assets/cfd41656-0786-47ff-a7f9-fb91c5c1a6a8)

I then redownloaded and reinstalled the mods completely from scratch; the only difference between my first attempt and second is that on the second, I went much slower with downloading mods, assuming maybe it was some corruption issue, then selected them all and click `Install`. At this point, I get something different: the game launched for a split second (modded based on the tweaked colors), then presumably crashed, and finally on subsequent launches would launch *without mods*. I should have taken a video of that first launch, but here's a video of the launch right after the first:

https://github.com/user-attachments/assets/985bd41d-df2d-416f-81c0-58972c4df0d1

[Log file for session shown in the video](https://github.com/user-attachments/files/19401339/nexusmods.app.main.current.log)

And that's pretty much all I have at this point

## Steps to reproduce
^ See above for in-depth, since I'm not sure if this can even be reproduced exactly, but the condensed version is:
- Have Stardew Valley installed with mods manually managed
- Launch Nexus Mods and create a loadout
- Migrate from manually managed mods to installed through the app
- Apply loadout, and try to launch Stardew Valley, only to find it can't be launched
- Reinstall Stardew Valley and delete the config made by the app in `~/.local/share/NexusMods.App`
- Launch app again and reinstall mods *slowly, one by one*, then select them all and click `Install`
- Apply loadout and try launching Stardew Valley

## What is the expected behaviour?
For Stardew Valley to at least launch on the first attempt

## Other information
- OS: Arch Linux
- Install method for Stardew Valley: Heroic Launcher Flatpak (`2.15.2`)
- Desktop: KDE Plasma 6.3.3
- Nexus Mods app version: `0.8.2.0`
- Stardew Valley version: `1.6.3`
- List of mods:

![List of Stardew Valley mods](https://github.com/user-attachments/assets/c2606d0d-59ee-40c5-82c7-8908b41f6866)

Apologies by the way for the long bug report, I try to be as comprehensive as possible.

**Comment by Al12rs** [comment]
Hi, thanks for the report!

We have identified a bug with the Apply operation that would not correctly update the files in External Changes, instead always preferring the first version of the file that ended up on there.

We have implemented a fix for this bug in:
- #2919
 
We should have a new release on Monday containing the fix!


For issue you have run into in particular, with the SMAPI deps.json file, you will likely have to go in your External Changes page and delete the entries found there. Ensure that the game files are verified with Heroic launcher and Apply again.

**Comment by Al12rs** [comment]
@StandingPadAnimations New app version is up with the fix is available here:
https://github.com/Nexus-Mods/NexusMods.App/releases/tag/v0.8.3

After installing the update, you might want to backup your game folder and reset it to vanilla state with your game store (Steam, GOG, Heroic).
Then inside the App you should delete the contents of the External Changes page.
That should fix the `Unable to extract {Game}/StardewModdingAPI.deps.json`.
After that I would suggest installing SMAPI inside the app rather than directly, as it should make things smoother.

Feel free to open a new ticket or talk to us on discord if you have more issues like this!

**Comment by Sewer56** [comment]
I'm reopening it because I'm still curious how the user even got to that state.

This is the second case where a user's game files ended up in overrides, as opposed to being part of the 'game installation' so to soeak.

**Comment by Al12rs** [comment]
Could you show us the contents of your External Changes page now, after you have tried to Apply with the new version? Did it get filled up again or did it stay empty?

My current guess is that the app did something wrong when the game was first managed and we might need to unmanage it and manage it again after making sure the game folder is vanilla again.

But that will remove your currently installed mods from the app and they will have to be installed again.

**Comment by Al12rs** [comment]
Ok, that is good to see at least, I guess the issue is with the initial game state for some reason.

In this case I would go ahead and unmanage Stardew from the app. 
Then go in the app settings and set log level to debug.
After the app Is closed I would ensure the game folder is in vanilla state by verifying with heroic (not sure if you need to delete the folder and redownload the game or what heroic offers).

Then manage the game again with the app and collecting the logs of that session. 
Hopefully it works now with 0.8.3 but in case it doesn't those logs could help understand what is going wrong.

**Comment by StandingPadAnimations** [comment]
> Ok, that is good to see at least, I guess the issue is with the initial game state for some reason.
> 
> In this case I would go ahead and unmanage Stardew from the app. Then go in the app settings and set log level to debug. After the app Is closed I would ensure the game folder is in vanilla state by verifying with heroic (not sure if you need to delete the folder and redownload the game or what heroic offers).
> 
> Then manage the game again with the app and collecting the logs of that session. Hopefully it works now with 0.8.3 but in case it doesn't those logs could help understand what is going wrong.

Performed those steps, still have the issue. Here's the log: [nexusmods.app.main.current.log](https://github.com/user-attachments/files/19480123/nexusmods.app.main.current.log)

**Comment by erri120** [comment]
This might actually be related to #2887, I'm currently investigating.

**Comment by StandingPadAnimations** [comment]
Good news and bad news: I finally got to test 0.9.2. After doing a fresh install of Stardew Valley, and then unmanaging and remanaging the game in the launcher, I no longer get an error related to missing game files

![Image](https://github.com/user-attachments/assets/1867a541-0c47-4acb-9bce-8eaa4b3a7667)

As for the bad news: when I go to launch the game, it open Heroic Launcher, and then... nothing. The game is reported as "playing", but no window pops up. In addition, I also get errors that look like the following:
```
System.FormatException: 0.0.0 isn't a valid semantic version. At least one of the major, minor, and patch numbers must be more than zero.
   at StardewModdingAPI.Toolkit.SemanticVersion.AssertValid() in /_/extern/SMAPI/src/SMAPI.Toolkit/SemanticVersion.cs:line 345
   at StardewModdingAPI.Toolkit.SemanticVersion..ctor(String version, Boolean allowNonStandard) in /_/extern/SMAPI/src/SMAPI.Toolkit/SemanticVersion.cs:line 104
   at NexusMods.Games.StardewValley.Emitters.Helpers.GetGameVersion(ReadOnly loadout) in /_/src/Games/NexusMods.Games.StardewValley/Emitters/Helpers.cs:line 42
   at NexusMods.Games.StardewValley.Emitters.DependencyDiagnosticEmitter.Diagnose(ReadOnly loadout, CancellationToken cancellationToken)+MoveNext() in /_/src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs:line 42
   at NexusMods.DataModel.Diagnostics.DiagnosticManager.<>c__DisplayClass8_0.<<GetLoadoutDiagnostics>b__0>d.MoveNext() in /_/src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs:line 92
--- End of stack trace from previous location ---
   at NexusMods.DataModel.Diagnostics.DiagnosticManager.<>c__DisplayClass8_0.<<GetLoadoutDiagnostics>b__0>d.MoveNext() in /_/src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs:line 92
``` 

Here's the log for the new session

[nexusmods.app.main.current.log](https://github.com/user-attachments/files/19660741/nexusmods.app.main.current.log)

**Comment by erri120** [comment]
@StandingPadAnimations could you check your Stardew Valley installation and see if you have the `Stardew Valley.dll` file? We get the game version by looking at that file.

**Comment by Sk4lli** [comment]
@StandingPadAnimations @erri120 
Sorry for Hijacking, i had the same issue with `System.FormatException: 0.0.0 isn't a valid semantic version.` 
this came up 4 times directly after switching to SdV within the app. 
After that i switched from Appimage to the AUR package. Still the same error.

while installing the AUR package i saw the note to remove the Appdata after upgrade.
After removing Nexusmod.APP data with
`rm -RF ~/.local/share/NexusMods.App`
.like suggested, the Prior error didn't showed up anymore.

Just while installing SMAPI through the app he couldn't find the Stardew Valley.deps.json

`(NexusMods.Games.StardewValley.Installers.SMAPIInstaller) Can't find the game file record for {Game}/Stardew Valley.deps.json`

i had to install SMAPI manually, the App still cant find the version but it work now with SMAPI (regular mod install also works.)

![Image](https://github.com/user-attachments/assets/b36f0023-b224-4d91-bfd4-86a76537d8db)

-  OS: Arch Linux x86_64 (EndeavourOS)
-  Install method for Stardew Valley: Heroic Launcher AUR (2.16.1) 
-  Desktop: KDE Plasma 6.3.5
-  Nexus Mods app version: 0.10.2.0
-  Stardew Valley version: 1.6.3
-  List of mods: none
